---
kind: pipeline
type: docker
name: mon-pipeline-ci
    
steps:
  - name: preact-app
    image: lowess/preact-cli
    commands:
      - preact create ${DRONE_REPO}#${DRONE_COMMIT} app
      - cd app
      - npm install
      - npm run build
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
        channel: drone-ci